# permissions for end users to edit helmcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmcomponent-editor-role
rules:
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - helmcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - helmcomponents/status
  verbs:
  - get
