# permissions for end users to view helmcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmcomponent-viewer-role
rules:
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - helmcomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - helmcomponents/status
  verbs:
  - get
