# permissions for end users to edit kymas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-editor-role
rules:
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - kymas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - kymas/status
  verbs:
  - get
