# permissions for end users to view kymas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-viewer-role
rules:
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - kymas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - kymas/status
  verbs:
  - get
