---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - helmcomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - helmcomponents/finalizers
  verbs:
  - update
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - helmcomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - networks/finalizers
  verbs:
  - update
- apiGroups:
  - inventory.kyma-project.io
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
