name: K3S test
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging'     
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2 
    - name: Prepare docker registry and k3s cluster
      run: |
        ./create-cluster-k3s.sh
        while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
    - name: Build & deploy controller
      run: |
        make manifests
        make install 
        make docker-build docker-push IMG=registry.localhost:5000/kyma-operator:latest
        make deploy IMG=registry.localhost:5000/kyma-operator:latest
        while [[ $(kubectl get deployment -n kymactl-system kymactl-controller-manager -o 'jsonpath={..status.availableReplicas}') != 1 ]]; do echo "Waiting for kymactl controller to be available"; sleep 2; done
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
    - name: Performance test
      run: |
        ./config/samples/sample-data.sh
